const URI = {
//  BASE_URL : "http://10.0.0.104:8080",
//  BASE_URL : "http://localhost:8080",
//  BASE_URL : "http://10.0.0.196:8080",
//  BASE_URL: "http://10.0.0.87:8080",
    BASE_URL: "http://ec2-18-222-232-226.us-east-2.compute.amazonaws.com:8080",
    LOOKUP_SCREEN_NAME: "/lookupScreenName",
    SIGNUP: "/signup",
    GET_PROFILE: "/getProfile",
    UPDATE_PROFILE: "/updateProfile",
    SEARCH_ORGANIZATION: "/searchOrganizations",
    CREATE_ORGANIZATION: "/createOrganization",
    GET_LIST_ORGANIZATION: "/listRequestOrganization",
    RESPOND_REQUEST: "/respondRequestOrganizaion",
    CREATE_UPDATE_HACKATHON: "/createUpdateHackathon",
    FETCH_PRICE: "/fetchPrice",
    LIST_HACKATHON: "/listHackathon",
    DETAIL_HACKATHON: "/detailHackathon",
    MAKE_PAYMENT: "/makePayment",
    REGISTER_HACKATHON: "/registerHackathon",
    SUBMIT_HACKATHON: "/submitCode",
    SAVE_GRADES:"/grade",
    GET_LEADERBOARD: "/leaderBoard",
    GET_FINANCIAL_REPORT:"/financialReport"
};
export default URI;